name: Delete Release Assets

# Configure a manual workflow trigger
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The tag of the release to delete assets from'
        required: true

# Define the job to run when the workflow is manually triggered
jobs:
  delete_assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant permission to write to contents for release management

    steps:
      - name: Delete assets from specified release
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.release_tag }}
          assets: 'v*'
          fail-if-no-release: true
          fail-if-no-assets: false
